application: s-t-h-c
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /js
  static_dir: js


- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: s-t-h-c.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest